### ISSUE TITLE
Bluetooth stutters

### ISSUE THREAD

**Issue by rp1231** [ysc3839/AudioPlaybackConnector#10]
Having audio stutters while using this.
Happened with the other uwp application that exists.
Do you have any idea how to solve it?

Also, thanks for making this!
It was much needed.

**Comment by Atrello** [comment]
I also have this issue, would love a fix as I'm trying to use this to stream from my TV to my PC to use wireless headphones :(

**Comment by ysc3839** [comment]
Sorry, I have no idea. This program is just a front-end for the underlying system API. The connection and transmission is handled by the system.

**Comment by mkanet** [comment]
I wonder what's the difference between those of us that don't have this issue and the ones that do.  I use my Samsung Note 9 to connect to my HTPC/Gaming PC via bluetooth without any stuttering issues when sending audio.  It actually very reliable.

**Comment by ysc3839** [comment]
I guess it's hardware issue. Maybe caused by cheap Bluetooth module or bad antenna.

**Comment by rp1231** [comment]
Using the intel bluetooth wireless chip that came installed with the laptop.....
Have ordered a usb dongle to see if it makes any difference. Will post my findings here in a few days after it arrives.

**Comment by Atrello** [comment]
I use this
https://www.amazon.co.uk/TP-LINK-UB4A-Bluetooth-Computer-Receiver/dp/B07YLDVM6B/
exact model of Bluetooth adapter, I think it must be a system side issue.

**Comment by rp1231** [comment]
Switching to a usb dongle solved my stuttering problems.
So I guess the problem was with my laptop's internal bluetooth card after all.

**Comment by Atrello** [comment]
Hmm weird, I still get the issue with a Bluetooth dongle.

**Comment by Atrello** [comment]
I am on desktop so it's my only option

**Comment by ShadowFlare** [comment]
There's likely interference coming from the computer on the 2.4 GHz frequency band, which Bluetooth also uses. Plugging in the receiver with some type of USB extension to move it away from the computer should help considerably, and some receivers (whether Bluetooth or for any other wireless peripheral) even come with some type of extender for this very reason (either just a short extension with no cord or an extension cord).

**Comment by Atrello** [comment]
Maybe, I mean I do have a wireless headset that uses 2.4g but that's on a
massive extension across my room and my mouse but that's it

**Comment by ShadowFlare** [comment]
I don't even mean things that use wireless communication are giving off the interference. Some components that don't even have anything to do with anything wireless whatsoever just give off interference in that frequency band or others. USB3 is one known source of interference in the 2.4 GHz band, though there can be any number of other components giving off interference in various frequency bands. Basically any electronic components that are unshielded will give off some form of radio signals. The best way to deal with this is to move the antenna away from the source of interference (the computer), which in this case the antenna is integrated with the receiver in the USB Bluetooth receiver. Moving it away from the computer with a USB extension can significantly reduce Bluetooth lag and stutters and can sometimes improve range substantially.
