### ISSUE TITLE
我无法使用手机调节输出到电脑的音量

### ISSUE THREAD

**Issue by qsbird** [ysc3839/AudioPlaybackConnector#14]
如题，无论手机显示的蓝牙音量大小是多少，电脑端播放的音量都不会随之改变，我使用Bluetooth Audio Receiver时也遇到了同样的问题，我不知道其他人有没有类似的问题，有人能帮我分析一下原因或者解决方法吗，非常感谢

**Comment by ysc3839** [comment]
我这里测试是没问题的，可能是不同设备蓝牙实现有差异。这种问题没什么好办法解决，这个项目只是调用系统的功能。
