### ISSUE TITLE
Windows 服务主进程使用麦克风

### ISSUE THREAD

**Issue by aliensvx** [ysc3839/AudioPlaybackConnector#2]
![image](https://user-images.githubusercontent.com/7090204/86306681-7d5a6f00-bc47-11ea-8347-db1a10d35911.png)
连接手机后播放音乐，任务栏提示一个应用正在使用你的麦克风。停止播放、断开连接、退出AudioPlaybackConnector依旧会提示，手动关闭麦克风提示才能消失。是否正常呢？
Windows 10 专业版 2004 
AudioPlaybackConnector v1.1.1

**Comment by ysc3839** [comment]
是正常的。这是因为 Windows 是通过录音设备+监听实现此功能，监听是 Windows Audio 服务自己录音再放出，所以会显示 svchost.exe。同时在断开连接后并不会自动关闭监听功能，所以会一直显示。
想要隐藏的话可以手动把监听关掉。
