### ISSUE TITLE
adding bluetooth call feature

### ISSUE THREAD

**Issue by SunnyKentz** [ysc3839/AudioPlaybackConnector#38]
Is there a way to add not only the Bluetooth audio feature but the Bluetooth call feature?
I would like to be able to receive calls when i have my headsets connected to my computer.

If anything can someone at least guide me to show how i could implement this in pull request?

https://github.com/ysc3839/AudioPlaybackConnector/assets/94718699/13f3cc43-f15f-405f-807a-bb07cbaa97ee

**Comment by ysc3839** [comment]
No. Windows does not provide such feature at this time.
