### ISSUE TITLE
手机蓝牙非“媒体”声音会在手机外放

### ISSUE THREAD

**Issue by LadderOperator** [ysc3839/AudioPlaybackConnector#4]
首先感谢开发者制作了这个工具！

在实际使用中，我发现虽然耳机会一直同步声音，但是通话等情形还是会自动外放（我是MIUI12），不知道这个问题是不是ROM问题？有办法修正吗？那个非开源版本同样有这个问题。

**Comment by ysc3839** [comment]
这是 Windows 的问题。
这个工具只是调用系统 API 连接设备，音频传输是 Windows 实现的，没办法修正。

**Comment by LadderOperator** [comment]
> 这是 Windows 的问题。
> 这个工具只是调用系统 API 连接设备，音频传输是 Windows 实现的，没办法修正。

感谢回复！我再研究研究
