### ISSUE TITLE
您好，編譯一直沒通過

### ISSUE THREAD

**Issue by ShiverZm** [ysc3839/AudioPlaybackConnector#5]
![image](https://user-images.githubusercontent.com/26861023/93286267-6fa99400-f809-11ea-8924-4fd4a65ae111.png)

**Comment by ysc3839** [comment]
怀疑 Visual Studio 没有安装 UWP C++ 开发组件？

**Comment by ShiverZm** [comment]
您好，创建了一个uwp c++的项目 是可以启动的
![image](https://user-images.githubusercontent.com/26861023/93292975-7213ea00-f819-11ea-89ab-981cdf623a07.png)

**Comment by ysc3839** [comment]
那有可能是没有安装 19041 的 SDK。

**Comment by ShiverZm** [comment]
是的 感謝 確實是少了win10 sdk 19041 已解決
