### ISSUE TITLE
Play on connect

### ISSUE THREAD

**Issue by md0-code** [ysc3839/AudioPlaybackConnector#9]
Would it be possible to trigger a play command on connect? It's tedious to  keep  goig on the phone to start playing audio after each connection...
Thanks

**Comment by ysc3839** [comment]
No, because Windows doesn't provide such API.

**Comment by utkarshsethi** [comment]
@md0-code 

You can set that on your Phone.

My phone automatically plays audio when it connect to Bluetooth device.

I've a setting for your phone not Windows.

It will be called something like => resume playback when connecting to headphones
